version: '3.9'

services:
  api:
    build: .
    container_name: okies_core_api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: okies_core_postgres
    restart: always
    environment:
      POSTGRES_USER: okies
      POSTGRES_PASSWORD: okies_pass
      POSTGRES_DB: okies_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: okies_core_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
